2022-09-01 12:40:08,369 [accelerator.module.AW.scrapers.AW_Google] ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/app/core/async_client/async_client.py", line 97, in receive_message
    incoming_message=accelerator_incoming_message)
  File "/app/core/async_client/async_client.py", line 231, in start_processing_massage
    await self.process_message(incoming_message)
  File "/app/core/scrapers/scraper.py", line 27, in process_message
    await getattr(self, callback)(message, message_body)
  File "/app/scrapers/scraper_AW/scraper_google.py", line 225, in extract_company_reviews
    rating = ''.join(x for x in rating if x.isdigit())
TypeError: 'NoneType' object is not iterable



2022-09-01 14:39:28,017 [accelerator.module.AW.scrapers.AW_FS] ERROR: time data 'Novembre 22, 2014' does not match format '%B %d, %Y'
Traceback (most recent call last):
  File "/app/core/async_client/async_client.py", line 97, in receive_message
    incoming_message=accelerator_incoming_message)
  File "/app/core/async_client/async_client.py", line 231, in start_processing_massage
    await self.process_message(incoming_message)
  File "/app/core/scrapers/scraper.py", line 27, in process_message
    await getattr(self, callback)(message, message_body)
  File "/app/scrapers/scraper_AW/scraper_FS.py", line 184, in extract_company_reviews
    datetime_photo = datetime.strptime(datetime_photo, '%B %d, %Y')
  File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data 'Novembre 22, 2014' does not match format '%B %d, %Y'


2022-09-01 14:38:47,167 [accelerator.module.AW.scrapers.AW_FS] ERROR: time data 'Şubat 15, 2013' does not match format '%B %d, %Y'
Traceback (most recent call last):
  File "/app/core/async_client/async_client.py", line 97, in receive_message
    incoming_message=accelerator_incoming_message)
  File "/app/core/async_client/async_client.py", line 231, in start_processing_massage
    await self.process_message(incoming_message)
  File "/app/core/scrapers/scraper.py", line 27, in process_message
    await getattr(self, callback)(message, message_body)
  File "/app/scrapers/scraper_AW/scraper_FS.py", line 184, in extract_company_reviews
    datetime_photo = datetime.strptime(datetime_photo, '%B %d, %Y')
  File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data 'Şubat 15, 2013' does not match format '%B %d, %Y'


2022-09-02 14:46:08,041 [accelerator.module.AW.scrapers.AW_FS] ERROR: unsupported operand type(s) for +=: 'NoneType' and 'str'
Traceback (most recent call last):
  File "/app/core/async_client/async_client.py", line 97, in receive_message
    incoming_message=accelerator_incoming_message)
  File "/app/core/async_client/async_client.py", line 231, in start_processing_massage
    await self.process_message(incoming_message)
  File "/app/core/scrapers/scraper.py", line 27, in process_message
    await getattr(self, callback)(message, message_body)
  File "/app/scrapers/scraper_AW/scraper_FS.py", line 181, in extract_company_reviews
    full_text += extended_text
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'


2022-09-03 13:01:26,026 [accelerator.module.AW.scrapers.AW_TA] ERROR: invalid literal for int() with base 10: 'cean_City_Cape_May_County_New_Jersey'
Traceback (most recent call last):
  File "/app/core/async_client/async_client.py", line 97, in receive_message
    incoming_message=accelerator_incoming_message)
  File "/app/core/async_client/async_client.py", line 231, in start_processing_massage
    await self.process_message(incoming_message)
  File "/app/core/scrapers/scraper.py", line 27, in process_message
    await getattr(self, callback)(message, message_body)
  File "/app/scrapers/scraper_AW/scraper_TA.py", line 172, in extract_company_info
    detail = int(url_data[2][1:])
ValueError: invalid literal for int() with base 10: 'cean_City_Cape_May_County_New_Jersey'


/app/scrapers/scraper_AW/scraper_TA.py\", line 184, in extract_company_info\n    total_photos = int(total_photos)\nValueError: invalid literal for int() with base 10: '1,480'


https://www.tripadvisor.com/Attraction_Review-g34601-d12971283-Reviews-10th_Street_Produce-Saint_Cloud_Florida.html
File \"/app/scrapers/scraper_AW/scraper_TA.py\", line 118, in extract_company_info\n    script = script[script.find('{'):script.find(';(this')]\nAttributeError: 'NoneType' object has no attribute 'find'


